import type { Metadata } from 'next'
import './globals.css'
import Link from "next/link"


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background text-foreground">
        <header className="border-b">
          <div className="container flex h-14 items-center justify-between">
            <Link href="/" className="font-semibold">
              CodeSphere
            </Link>
            <nav className="flex gap-4 text-sm">
              <Link href="/problems">Problems</Link>
              <Link href="/login">Login</Link>
            </nav>
          </div>
        </header>

        <main className="container py-6">{children}</main>
      </body>
    </html>
  )
}

